create table if not exists players (
  id bigint generated by default as identity primary key,
  provider_id int unique not null,
  name text not null,
  position text,
  nationality text,
  date_of_birth date,
  shirt_number int,
  contract_until date,
  market_value bigint,
  updated_at timestamptz not null default now()
);

create table if not exists matches (
  id bigint generated by default as identity primary key,
  provider_id int unique not null,
  utc_date timestamptz not null,
  local_date_rome timestamptz not null,
  competition text,
  home_team text not null,
  away_team text not null,
  home_score int,
  away_score int,
  status text not null,
  updated_at timestamptz not null default now()
);

create table if not exists cache_meta (
  key text primary key,
  updated_at timestamptz not null default now(),
  ttl_seconds int not null
);

create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

create or replace function touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_players_updated_at
before update on players
for each row execute function touch_updated_at();

create trigger trg_matches_updated_at
before update on matches
for each row execute function touch_updated_at();

